[package]
name = "games"
version = "0.1.0"
authors = ["Juan Rodriguez <sjdonado.de>"]
edition = "2021"

[lib]
path = "logic/games.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
gloo-utils = { version = "0.1", features = ["serde"] }
